public class ClassToBeTested {
    public static Integer addNumbers(Integer a, Integer b) {
        Integer sum = a + b;
        return sum;
    }
//Conflict resolved to incorporate WIP in Dev2 to Updates from UAT
    
     public static Integer substractNumbers(Integer a, Integer b) {
        Integer substract = a - b;
        return substract;
    }
    
     public static Integer multiplyNumbers(Integer a, Integer b) {
        Integer multiply = a * b;
        return multiply;
    }
}
