public class ClassToBeTested {
    public static Integer addNumbers(Integer a, Integer b) {
        Integer sum = a + b;
        return sum;
    }
    //Comment on Dev1 for Copado Updates test - Feature Branch 1
    //Comment 2 on Dev1 for Copado Update test - Feature Branch 2
    //Comment 3 on Dev1 for Copado Update test - Feature Branch 2
    
     public static Integer substractNumbers(Integer a, Integer b) {
        Integer substract = a - b;
        return substract;
    }
    
     public static Integer multiplyNumbers(Integer a, Integer b) {
        Integer multiply = a * b;
        return multiply;
    }
}